Made the script extensible

diff --git a/dbox b/dbox
--- a/dbox
+++ b/dbox
@@ -1,6 +1,14 @@
 #!/usr/bin/bash
 
-DBOX_HOME_FOLDER="$HOME/Documents/1.projects" 
+# Guards
+if [ -z "$DBOX_HOME_FOLDER" ]; then
+	echo "ERROR! The DBOX_HOME_FOLDER must be set to the directory you want the containers to base their home directory in."
+	exit 2
+elif [ -z "$DBOX_PROVISION_SCRIPT_LOC" ]; then
+	echo "ERROR! DBOX_PROVISION_SCRIPT_LOC must be set to provision the container once initialized."
+	exit 2
+fi
+
 
 dbox_help() {
 	  printf "Thin wrapper around distrobox that makes the most commonly used commands painless.\n\nUSAGE:\tdbox <COMMAND> <ARGS>\n\nCOMMANDS:\n\tcreate: Creates a distrobox with the given name at DBOX_HOME_FOLDER.\n\tenter: Enters into the given container."
@@ -14,7 +22,7 @@ dbox_create() {
 	mkdir -p "$INTERNAL_HOME_FOLDER" 2>/dev/null
 
 	echo "Copying provision script..."
-	cp "$HOME/Documents/4.archives/2.scripts/provision" "$INTERNAL_HOME_FOLDER"
+	cp "$DBOX_PROVISION_SCRIPT_LOC" "$INTERNAL_HOME_FOLDER"
 
 	distrobox create -n "$1" -H "$INTERNAL_HOME_FOLDER" --additional-packages "git neovim ripgrep zoxide eza bat clang zig nodejs"
 
diff --git a/nv b/nv
--- a/nv
+++ b/nv
@@ -1,12 +1,17 @@
 #!/usr/bin/bash
 
-PROJECT_DIRS="$HOME/Documents/1.projects $HOME/Documents/4.archives/1.projects"
-
+# Guards
+if [ -z "$PROJECT_DIRS" ]; then
+	echo "ERROR! Project base folder(s) not set with PROJECT_DIRS"
+	exit 2
+fi
+	
 if ! command -v fzf 2>&1 >/dev/null; then
 	echo "Please install fzf to use this utility."
 	exit 2
 fi
 
+# The fun stuff
 if [ $# -eq 1 ]; then
 	if [ $1 = "help" ]; then
 		printf "Opens project directory in neovim and optionally restores the project to its last session.\nPlease note that if there is no session saved for a project, the session restore option will open a blank screen.\n\nUSAGE:\tnv [-r]\n\nOPTIONS\n\t-r\tRestore Previous Session"
